// next
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// // styled components
// import styled, { ThemeProvider } from "styled-components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spectrum Tracker",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACKUlEQVR4AcWWA5MkURCE+2zbtu27wNm2bTu0e7Zt27Zt28bY/rYrdn/CzpucaQVeOSs1IAMwBzCgDiZgAZBJizPuRT18wGIN+E/kYNGIMMLuQDAYxO32EAqF1Doghj9++saaDXu4e/+pugz4fD4ePn7J+KnzKFahMdGzVuDxeMPvgN3h5OyFG/ToP5Es+WqQIHlhho2JxuF0ha8HpK5//xnZtusIDVv2JVWW8mjJCulXYbr2HofJZAlPE0p9P3z8yrzFG6hYqw1J0paMNZyyKJoeeaNW/fjx80/8T4HL5ebWnUeMGDedPEXroSUpKFes4VTFJHKq1evA23ef438MXW43h4+fZ8ioKNp2GU67riPo1HM0VXWDYlwiL6433f2Hz8PDA5J2r9eH3+8nEAjKNxaLjTadh6ElLUjuInU5f+mmWiJatHwziVIXJ2OuKuw9cEotE0ov5CxYixQZy7Bq3S7JiDoH/htMNGjeh0R67afNXinko24XSKRRM5eTWDcu0+B0utQuI2G7THrNu/QaK0SjdhsKuVSv10FPf29+/Pqrdh37fH5Gjp9B1brthWjU64F9B09TuU477j14pl6QvHv/mSZtBnDm/HX1iki6fPzUuezedyIykmzvwVNs2nZA6Fe9A6/ffmSXHrnb41EvSh0OF9dvPcBmc0RGFRsMJmx2R2RkuUgtoVx5qndAMTTAQORg1YAFgA/18AMrNCATsBiwoQ52MQ5kjQEylU9chatfPQAAAABJRU5ErkJggg==",
    },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body style={{backgroundColor: "#020617"}} className={inter.className}>{children}</body>
      </html>
    </>
  );
}

